# Generated by Django 3.2.6 on 2021-08-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announced_lga_results',
            fields=[
                ('result_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('lga_name', models.CharField(max_length=50, null=True)),
                ('party_abbreviation', models.CharField(max_length=4, null=True)),
                ('party_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announced_state_results',
            fields=[
                ('result_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50, null=True)),
                ('party_abbreviation', models.CharField(max_length=4, null=True)),
                ('party_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announced_ward_results',
            fields=[
                ('result_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=50, null=True)),
                ('party_abbreviation', models.CharField(max_length=4, null=True)),
                ('party_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('uniqueid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('lga_id', models.IntegerField(blank=True, null=True)),
                ('lga_name', models.CharField(max_length=50, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('lga_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('partyid', models.CharField(max_length=11, null=True)),
                ('partyname', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polling_unit',
            fields=[
                ('uniqueid', models.IntegerField(primary_key=True, serialize=False)),
                ('polling_unit_id', models.IntegerField(blank=True)),
                ('ward_id', models.IntegerField(blank=True, null=True)),
                ('lga_id', models.IntegerField(blank=True, null=True)),
                ('uniquewardid', models.IntegerField(null=True)),
                ('polling_unit_number', models.CharField(max_length=50, null=True)),
                ('polling_unit_name', models.CharField(max_length=50, null=True)),
                ('polling_unit_description', models.TextField(null=True)),
                ('lat', models.CharField(max_length=255, null=True)),
                ('long', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('uniqueid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ward_id', models.IntegerField(null=True)),
                ('ward_name', models.CharField(max_length=50, null=True)),
                ('lga_id', models.IntegerField(null=True)),
                ('ward_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announced_pu_results',
            fields=[
                ('result_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('party_abbreviation', models.CharField(max_length=4, null=True)),
                ('party_score', models.IntegerField(null=True)),
                ('polling_unit', models.ForeignKey(db_column='polling_unit_uniqueid', on_delete=django.db.models.deletion.CASCADE, to='polls.polling_unit')),
            ],
        ),
        migrations.CreateModel(
            name='Agentname',
            fields=[
                ('name_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('pollingunit_uniqueid', models.ForeignKey(db_column='pollingunit_uniqueid', on_delete=django.db.models.deletion.CASCADE, to='polls.polling_unit')),
            ],
        ),
    ]
